name: s3backup
version: '1.1.0'
main: cloud.stonehouse.s3backup.S3Backup
api-version: '1.14.4'

commands:
  s3backup:
    description: Displays info for s3backup.
    permission: s3backup

permissions:
  s3backup.*:
    description: Allow the use of all s3backup commands.
    children:
      s3backup: true
      s3backup.backup: true
      s3backup.delete: true
      s3backup.get: true
      s3backup.list: true
      s3backup.sign: true
  s3backup:
    description: Allow displaying s3backup info.
  s3backup.backup:
    description: Allow creation of backups.
    children:
      s3backup: true
  s3backup.delete:
    description: Allow deletion of backups.
    children:
      s3backup: true
  s3backup.get:
    description: Allow downloading backups to the server backup directory.
    children:
      s3backup: true
  s3backup.list:
    description: Allow the listing of backups.
    children:
      s3backup: true
  s3backup.sign:
    description: Allow downloading backups locally by generating a signed URL.
    children:
      s3backup: true
