name: s3backup
version: '1.0'
main: cloud.stonehouse.s3backup.S3Backup
api-version: '1.14'

commands:
  s3backup:
    description: Initiate a backup. Optional list/get/delete subcommands.
    usage: /s3backup (list) (get|delete (backup))
    permission: s3backup.use

permissions:
  s3backup.use:
    description: Allows the use of the s3backup commands.